Restaurants
saarSAARsaar/postcode-search pull request #3
Opened 2020-09-17 14:53 UTC by saarSAARsaar

A place now has many restaurants, can be displayed

2020-09-24 11:55 UTC, TatianaPan requested changes
Looks good! I left some comments.
Also, let's try to have one empty line at the end of each file - it's like a Ruby standard :)

2020-09-24 11:55 UTC, TatianaPan commented on app/views/restaurants/index.html.erb
> +            <th colspan="2"></th>
Do we need `<th colspan="2"></th>`?

2020-09-24 11:55 UTC, TatianaPan commented on test/fixtures/restaurants.yml
> +one:
I would suggest to give this example more meaningful name, so it will be easier to use in tests, sometheing like `lausanne_restaurant_1`instead of `one`. What do you think?

2020-09-24 11:55 UTC, TatianaPan commented on test/models/restaurant_test.rb
> +    assert restaurant.errors.to_a, "Name can't be blank"
I would suggest to use in such tests `assert_equal` instead of `assert`, because we compare 2 instances and check if they are equal

2020-09-24 11:55 UTC, TatianaPan commented on test/models/restaurant_test.rb
> +    assert restaurant.name, 'Test restaurant name'
Same as previous comment

2020-09-24 11:55 UTC, TatianaPan commented on test/system/restaurants_test.rb
> +        assert 'body > table > tbody > tr:first > td:first', 'Test restaurant name'
Let's also use `assert_equal` here

2020-09-24 11:55 UTC, TatianaPan commented on test/system/restaurants_test.rb
> +        visit root_path
we can check first if place is on the page, something like:
```
within 'body > table > tbody > tr:first'
  assert_selector 'td', text: 'Lausanne'
end
```

2020-09-24 11:55 UTC, TatianaPan commented on test/system/restaurants_test.rb
> +        assert 'body > table > tbody > tr:first > td:first', 'Test restaurant name'
Or `assert_selector` even better for system test

2020-09-24 11:55 UTC, TatianaPan commented on test/controllers/restaurant_controller_test.rb
> +class RestaurantControllerTest < ActionDispatch::IntegrationTest
Let's add some controller tests

2020-09-24 12:20 UTC, saarSAARsaar commented on test/fixtures/restaurants.yml
> +one:
Ok

2020-09-24 12:21 UTC, saarSAARsaar commented on app/assets/stylesheets/restaurant.scss
> +// Place all the styles related to the Restaurant controller here.
Just that css file?

2020-09-24 12:22 UTC, saarSAARsaar commented on app/controllers/places_controller.rb
> +    def get_shark
Changed to make more sense

2020-09-24 12:23 UTC, saarSAARsaar commented on app/helpers/restaurant_helper.rb
> +module RestaurantHelper
Just that helper?

2020-09-24 12:25 UTC, saarSAARsaar commented on app/views/restaurants/index.html.erb
> +            <th colspan="2"></th>
Apparently not

2020-09-24 12:26 UTC, saarSAARsaar commented on test/controllers/restaurant_controller_test.rb
> +class RestaurantControllerTest < ActionDispatch::IntegrationTest
Done

2020-10-07 08:44 UTC, TatianaPan commented on app/assets/stylesheets/restaurant.scss
> +// Place all the styles related to the Restaurant controller here.
yes

2020-10-07 08:44 UTC, TatianaPan commented on app/helpers/restaurant_helper.rb
> +module RestaurantHelper
yes

2020-10-07 09:14 UTC, TatianaPan commented on app/views/layouts/_alerts.html.haml
> +%alert= alert
We can remove this file since this way of showing alerts didn't work

2020-10-07 09:17 UTC, TatianaPan commented on app/views/restaurants/index.html.erb
> +<%= flash[:notice] %>
It would be better to move it to `/app/views/layouts/application.html.erb` - so that flash messages will be displayed on any page if needed, not only for Restaurants.

2020-10-07 09:46 UTC, ahorincar reviewed
Thanks for your work, looks good! Only had some minor comments.

I also wanted to mention that it seems like your editor is configured to use indentation of 4 spaces (or 2 tabs? not sure). Typically, the standard in Ruby is to use indentation of 2 spaces so I was wondering if you could switch to using that? Note that for other languages the standard may be to use 4 spaces, but in Ruby we use 2. 

I would propose the following:
- changing the configuration of indentation in your editor so that it uses 2 spaces
- on a separate, new branch (from master) you can update all existing Ruby files in the app to use 2 spaces. It should be possible to do this automatically using the editor I think. Maybe you can research how to do this automatically?

2020-10-07 09:46 UTC, ahorincar commented on app/controllers/places_controller.rb
> +    def get_place
You can use a `before_action` hook to set the place for these actions. The advantage is that you avoid code duplication (so for example if you rename the `get_place` method, you only do it once, rather than 3 times).

See an example of what I mean here: https://stackoverflow.com/questions/45615591/how-does-only-at-before-action-work-in-rails

2020-10-07 09:46 UTC, ahorincar commented on app/controllers/places_controller.rb
> +    def get_place
Also, it's common to use the `set_` prefix for this method and initialise the instance variable there:
```ruby
def set_place
  @place = ...
end
```

2020-10-07 09:46 UTC, ahorincar commented on app/controllers/restaurants_controller.rb
> +    def get_place
As this is initialising an instance variable, I'd suggest renaming it to `set_place`.

2020-10-07 09:46 UTC, ahorincar commented on app/controllers/restaurants_controller.rb
> +        @restaurant = @place.restaurants.new()
You don't need to use `()` here, if no parameters are passed in to the method

2020-10-07 09:46 UTC, ahorincar commented on app/controllers/restaurants_controller.rb
> +    def edit
I am not 100% but I think Rails automatically generates this method if you don't provide one. So I think you can remove it (as it's empty anyway).

2020-10-07 09:46 UTC, ahorincar commented on app/controllers/restaurants_controller.rb
> +      @place = get_place()
The app is already calling this, because you added `before_action :get_place` at the top of the file (which means that the `get_place` method will be called for each action in this controller.

2020-10-07 09:46 UTC, ahorincar commented on app/models/search.rb
> +            return_places = Place.all
Is this adding or removing some whitespace? I am not sure 😁

2020-10-07 09:46 UTC, ahorincar commented on db/migrate/20200903141001_create_restaurants.rb
> +      t.string :name
Should this be a required field? What do you think?

2020-10-07 09:47 UTC, TatianaPan requested changes
Good job! I have just couple of small improvements notices.

2020-10-07 09:47 UTC, TatianaPan commented on test/system/restaurants_test.rb
> +        assert_selector 'body', text: 'Restaurant has been created'
Usually we can access flash message by class `notice`. You can also add a css class to flash[:notice] and then use this css class as selector in tests.

2020-10-07 09:47 UTC, TatianaPan commented on app/controllers/restaurants_controller.rb
> +
we don't have to `get_place` inside `destroy`, because we get place before all actions.
Also, `@restaurant` is available in `destroy` as well - we get it before_action. The function would look like this: 
```
def destroy
  @restaurant.destroy
  redirect_to @place, notice: 'Restaurant has been deleted.'
end
```

2020-10-07 09:47 UTC, TatianaPan commented on app/controllers/places_controller.rb
Let's add `before_action :get_place, only: %i[show edit update]`, remove `get_place` calls  from `show`, `edit` and `update` and modify `get_place`:
```
def get_place
  @place = Place.find(params[:id])
end
```

2020-10-22 12:04 UTC, saarSAARsaar commented on app/models/search.rb
> +            return_places = Place.all
Added, did not realise I did that

2020-10-22 12:05 UTC, saarSAARsaar commented on db/migrate/20200903141001_create_restaurants.rb
> +      t.string :name
A restaurant changing its name is possible and it doesn't really hurt to have

2020-10-22 12:08 UTC, saarSAARsaar commented on app/controllers/restaurants_controller.rb
> +
Can I leave out the notice?

2020-10-22 12:35 UTC, TatianaPan commented on app/controllers/restaurants_controller.rb
> +
yes

2020-10-29 09:35 UTC, TatianaPan approved these changes
Looks good! 👍  Let's merge it.

2020-10-29 13:09 UTC, merged